- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
  
    - name: install python pip
      yum:
        name: python-pip
        state: present
  
    - name: Downloading docker
      yum:
        name: docker
        state: present
        
    - name: install docker-py pip
      pip:
        name: docker-py
        state: present
        
    - name: starting docker daemon
      service:
          name: docker
          state: started
          
    - name: data container
      docker_container:
        name: mydata
        image: nj2497/nj24dockerlab:01
        state: started
        ports:
         - "9090:8080"


